export interface Todo_carga {
    id?: number,
    fecha_carga?: string,
    sucursal?: number,
    tienda?: number,
    boleta?: string,
    guia?: string,
    sku?: string,
    producto?: string,
    cantidad?: number,
    bulto?: number,
    cliente?: string,
    rut_cliente?: string,
    fono_cliente?: string,
    email_cliente?: string,
    direccion_cliente?: string,
    comuna_cliente?: string,
    fecha_compromiso?: string,
    lpn?: string,
    marcaPgd?: number
}